### ISSUE TITLE
Test dependencies not installed in virtualenv environment

### ISSUE THREAD

**Issue by nzjrs** [loopbio/imgstore#1]
What's the python packaging compliant way to declare these now?

* add `pytest pytest-cov pytest-pep8` to requirements.txt 
* some staza in setup.py
* other?

**Comment by sdvillal** [comment]
I do not really know. But I like to think this way: tests are part of the distribution, therefore the requirements for running them should be installed with the package. So if I should decide, I would just install them as regular dependencies (that is, your first solution).

setup.py has *tests_require* and I have put them in there, but people do not know how to use pip selectors. In the conda env I have just added them as regular deps.
