### ISSUE TITLE
Get list of all available `frame_number` values

### ISSUE THREAD

**Issue by jgraving** [loopbio/imgstore#11]
I'm [writing a wrapper](https://github.com/jgraving/pinpoint/blob/master/pinpoint/StoreReader.py) around your imgstore class to make batching and iterating easier, and I'm wondering if there is a way to get all the available values of `frame_number` from the imgstore class. The class seems to know how many frames there actually are in the store, and if there are missing frames this doesn't match up with the the range `store.frame_max - store.frame_min`, but I can't seem to find a way to extract the `frame_number` values for the available frames.

**Comment by nzjrs** [comment]
`get_frame_metadata()` should do what you want I think. It returns a dict with at least `'frame_number` and `frame_time`.

If you want an extra ounce of performance I could change the prototype to `get_frame_metadata(what='all')` and only return what you want, or `get_all_frame_number()`. Just let me know

**Comment by jgraving** [comment]
Ah, seems obvious now. Not sure how I missed that. `get_frame_metadata()` works. Thanks!
