### ISSUE TITLE
OpenCV >=4.0 breaks import

### ISSUE THREAD

**Issue by jgraving** [loopbio/imgstore#13]
Tried using imgstore with opencv 4 and I get this error message. Simple downgrade to 3.4 fixed it, but wanted to let you know that there seem to be some API breaking changes.

~/.local/lib/python3.6/site-packages/imgstore/__init__.py in <module>
----> 1 from .stores import new_for_filename, new_for_format, extract_only_frame, get_supported_formats,\
      2     VideoImgStore, DirectoryImgStore
      3 from .apps import main_test
      4 from .util import ensure_color, ensure_grayscale
      5 

~/.local/lib/python3.6/site-packages/imgstore/stores.py in <module>
     36     DEVNULL = open(os.devnull, 'r+b')
     37 
---> 38 from .util import ImageCodecProcessor, JsonCustomEncoder, FourCC, ensure_color, ensure_grayscale
     39 
     40 

~/.local/lib/python3.6/site-packages/imgstore/util.py in <module>
     13 else:
     14     # noinspection PyUnresolvedReferences
---> 15     FourCC = cv2.cv.CV_FOURCC
     16 
     17 

AttributeError: module 'cv2.cv2' has no attribute 'cv'

**Comment by nzjrs** [comment]
thanks. it takes the wrong branch here, with is my bug and not an API break in OpenCV4 (although there might be others I guess)

https://github.com/loopbio/imgstore/blob/b8cbd8c7e186755ae03fe0b5ecafa671fe16495b/imgstore/util.py#L11
