### ISSUE TITLE
With newest motif recordings, get_extra_data() cannot find the extra data.

### ISSUE THREAD

**Issue by luigiferiani** [loopbio/imgstore#16]
get_extra_data() looks for chunk_number.extra.json, but after updating motif (at least on our system) the extra data is saved as chunk_number.**extra_data**.json and so the api cannot find it

**Comment by nzjrs** [comment]
this should have been fixed since 0.2.5? https://github.com/loopbio/imgstore/commit/aed9dc17633c2c30e673b89ceb9b90bcb0036e4e

which version do you have?

**Comment by luigiferiani** [comment]
ooh my bad, I'm on 0.2.3. Sorry about this
