### ISSUE TITLE
Mac: I think we do not need homebrew for opencv, conda should work

### ISSUE THREAD

**Issue by maxlklaxl** [loopbio/imgstore#8]

**Comment by nzjrs** [comment]
exactly, yeah. using conda-forge opencv packages (we dont build for mac)

**Comment by maxlklaxl** [comment]
@maxlklaxl  test on other mac too and adapt readme

**Comment by nzjrs** [comment]
> In a fresh environment on Mac, I suggest copying environment.yaml to environment-mac.yaml, 
> removing our channel and replacing all the other instances of "loopbio" with "conda-forge" and then 
> installing.
