### ISSUE TITLE
imgstore-view: limit window size with massive images

### ISSUE THREAD

**Issue by nzjrs** [loopbio/imgstore#9]
screen resolution on mac https://stackoverflow.com/questions/1281397/how-to-get-the-desktop-resolution-in-mac-via-python/44348431#44348431

@maxlklaxl  what is the output of typing `system_profiler SPDisplaysDataType` on Mac?

**Comment by nzjrs** [comment]
**just post lines that start with 'Resolution:'`**

**Comment by maxlklaxl** [comment]
on the air

```
maxhofbauer$ system_profiler SPDisplaysDataType
Graphics/Displays:

    Intel HD Graphics 4000:

      Chipset Model: Intel HD Graphics 4000
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x0166
      Revision ID: 0x0009
      Metal: Supported, feature set macOS GPUFamily1 v3
      Displays:
        Color LCD:
          Display Type: LCD
          Resolution: 1440 x 900 (Widescreen eXtended Graphics Array Plus)
          UI Looks like: 1440 x 900
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort
```

**Comment by nzjrs** [comment]
@maxlklaxl  please test imgstore-view if you are bored (watch for error messages)

**Comment by maxlklaxl** [comment]
not working for me
* window is not resizing

`
(imgstore) Johns-MacBook-Air:~ maxhofbauer$ imgstore-view mystore/metadata.yaml 
INFO:imgstore:old store detected. synthesizing created datetime / timezone
DEBUG:imgstore:found 1 chunks in in 0.000636s
DEBUG:imgstore:built index in 0.013966s
DEBUG:imgstore:frame range 0.000000 -> 99.000000
DEBUG:imgstore:loading chunk 0
CREATED WINDOW 225x225:0 (from (3000, 3000))`

**Comment by nzjrs** [comment]
> window is not resizing

this means 

1. it is not resizable with the mouse (it is large and you cant drag on the bottom corner to make it smaller)
2. it is very large (3000 x 3000)
3. both

**Comment by nzjrs** [comment]
fixed in https://github.com/loopbio/imgstore/commit/41d5b11374782ff4bee9c3534fdaa40cbe63624a

**Comment by nzjrs** [comment]
Immense crying

**Comment by nzjrs** [comment]
wontfix because the GUI backend for opencv is just terrible and doesnt support auto window sizing like on other platforms. dont use mac.
